on:
    push:
      branches:
      - staging
  name: Deploy to Test
  jobs:
    pushToTest:
      name: Push To Test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for npm
        uses: actions/setup-node@v1
        with:
          node-version: '10.15'
      - run: npm run-script build
      - name: GitHub Action for AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run : aws s3 cp /home/runner/work/sw-flow-trends/sw-flow-trends/build/ s3://test.wim.usgs.gov/sw-flow-trends/ --recursive
      - name: GitHub Action for Slack
        uses: Ilshidur/action-slack@9273a03
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: Successfully deployed to test site